name: Check plugins

on:
  push:
    branches: [ main ]
    paths:
      - 'plugins/**'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'plugins/**'
      - '.github/**'

jobs:
  check_plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 这样 git 命令能访问到所有标签

      - name: Set up Golang
        uses: actions/setup-go@v2

      - name: Bulid
        run: |
          go build -o ./bin/ ./plugins/...

      - name: Render and commit HTML
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_REPOSITORY: ${{ github.repository }}
#            CHANGED_FILES: ${{ steps.file_changes.outputs.files }}
        run: |
          cd web/workflow
          go mod tidy
          go run main.go
