name: Check plugins

on:
  push:
    branches: [ main ]
    paths:
      - 'plugins/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'plugins/**'

jobs:
  check_plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 这样 git 命令能访问到所有标签

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 可以根据您的 Python 版本进行修改

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Check plugins
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 添加这一行
          GITHUB_REPOSITORY: ${{ github.repository }}  # 添加这一行
        run: python .github/scripts/check-plugins.py plugins
