name: Check plugins

on:
  push:
    branches: [ main ]
    paths:
      - 'plugins/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'plugins/**'

jobs:
  check_plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 可以根据您的 Python 版本进行修改
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt
      - name: Check plugins
        run: python .github/scripts/check-plugins.py plugins
