name: Check plugins

on:
  push:
    branches: [ main ]

jobs:
  check_plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 这样 git 命令能访问到所有标签

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Set up Git
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"
            
            
      - name: Render and commit HTML
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_REPOSITORY: ${{ github.repository }}
#            CHANGED_FILES: ${{ steps.file_changes.outputs.files }}
        run: |
          cd web/workflow
          go mod tidy
          go run main.go

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Committing changes made by ${{ github.actor }} in GitHub Workflow"

      - name: Push Changes
        run: |
          git push origin main --tags